#!/bin/bash
#
#  usage: CC2Helper path k
#
#  where path is the path to the allocator and k is the
#  number of registers for the allocator to target.
#
#  Locations for the ILOC Simulator and the command
#  that actually runs the code are specified in the 
#  defined variables SIM and RUN
#
SIM=/clear/courses/comp412/students/lab2/sim
#SIM=~/MyFiles/Src/412/2016/sim/lab2/src/sim
RUN=/clear/courses/comp412/students/lab2/code_check_2/AllocOne
#RUN=./AllocOne
#
# and the test files
F1=/clear/courses/comp412/students/lab2/code_check_2/cc1.i
F2=/clear/courses/comp412/students/lab2/code_check_2/cc2.i
F3=/clear/courses/comp412/students/lab2/code_check_2/cc3.i
F4=/clear/courses/comp412/students/lab2/code_check_2/cc4.i
F5=/clear/courses/comp412/students/lab2/code_check_2/cc5.i
#
echo "Using k = ${2}"
echo "-----"
    $RUN $F1 $1 $2 $SIM
echo "-----"
    $RUN $F2 $1 $2 $SIM
echo "-----"
    $RUN $F3 $1 $2 $SIM
echo "-----"
    $RUN $F4 $1 $2 $SIM
echo "-----"
    $RUN $F5 $1 $2 $SIM
echo "-----"

#

